const UI_TEXTS = {
    pendingEmpty: "Nessuna richiesta in attesa.",
    adminNotFound: "Admin non trovato.",
    passwordsMismatch: "Le password non coincidono.",
    fieldsRequired: "Compila tutti i campi.",
    invalidEmail: "Email non valida.",
    invalidPhone: "Numero telefono non valido (prefisso +39 obbligatorio).",
    passwordUpdated: "Password aggiornata.",
    adminNameRequired: "Inserisci un nome valido.",
    adminSelectionRequired: "Seleziona un admin da modificare.",
    adminAlreadyExists: "Esiste gia un admin con questo nome.",
    adminUpdated: "Admin aggiornato.",
    adminAdded: "Admin aggiunto.",
    adminRemoved: "Admin rimosso.",
    adminMinRequired: "Deve esserci almeno un admin.",
    adminNone: "Nessun admin configurato.",
    adminAccessDescription: "Inserisci la password admin per aprire la gestione.",
    adminDeletePasswordDescription: (adminName) =>
        `Inserisci la password di ${adminName} per confermare la rimozione.`,
    passwordInvalid: "Password attuale non valida.",
    defaultAdminLabel: "Admin",
    requestEditPasswordDescription: "Inserisci la password per modificare la richiesta.",
    requestDeletePasswordDescription: "Inserisci la password per eliminare definitivamente la richiesta.",
    pendingApprovePasswordDescription: "Inserisci la password per approvare la richiesta.",
    pendingRejectPasswordDescription: "Inserisci la password per rifiutare la richiesta.",
    pendingAccessPasswordDescription: "Inserisci la password per visualizzare le richieste in attesa.",
    mutuaPasswordDescription: "Inserisci la password admin per confermare la mutua.",
    giustificatoPasswordDescription: "Inserisci la password admin per confermare il permesso giustificato.",
    specialePasswordDescription: "Inserisci la password admin per confermare il permesso chiusura aziendale.",
    hashingUnavailableTitle: "Modulo hashing non disponibile.",
    hashingUnavailableDetail: "Esegui 'npm install hash-wasm' nella cartella del progetto.",
    otpUnavailableTitle: "Modulo OTP non disponibile.",
    otpMailerMissingModule: "Modulo mancante: nodemailer.",
    otpMailerInstallerNote:
        "Se stai usando l'app installata, devi rigenerare l'installer per includere le nuove dipendenze.",
    otpMissingAdminName: "Inserisci il nome admin.",
    otpMissingAdminEmail: "Email admin mancante.",
    otpResendWait: (seconds) => `Attendi ${seconds}s prima di reinviare l'OTP.`,
    otpSent: "OTP inviato via email. Valido 5 minuti.",
    otpSendError: (detail) => `Errore invio email: ${detail}`,
    otpMissingCode: "Inserisci il codice OTP.",
    otpExpired: "OTP scaduto. Richiedi un nuovo codice.",
    otpUnavailableDetail: (detail) => `Dettaglio otplib: ${detail}`,
    otpUnavailableMessage: (detail) => `OTP non disponibile: ${detail}`,
    otpInvalid: "OTP non valido.",
    otpVerified: "OTP verificato. Imposta una nuova password.",
    otpVerifyFirst: "Verifica l'OTP prima di proseguire.",
    otpFillNewPasswords: "Compila le nuove password.",
    requestMissingFields: "Compila dipendente e periodo richiesto.",
    requestInvalidDateFormat: "Formato data non valido.",
    requestNoPastDates: "Non puoi inserire date precedenti a oggi.",
    requestEndBeforeStart: "La data fine non puo essere precedente alla data inizio.",
    requestEndTimeBeforeStart: "L'orario di fine non puo essere precedente all'inizio.",
    requestMultiDayAllDayOnly: "Per periodi di piu giorni serve giornata intera.",
    requestMissingTimes: "Inserisci orari di inizio e fine.",
    requestSent: "Richiesta inviata.",
    mutuaInserted: "Mutua registrata.",
    giustificatoInserted: "Permesso giustificato registrato.",
    holidayInvalidDate: "Seleziona una data valida.",
    holidayRangeInvalid: "Seleziona un intervallo valido.",
    holidayAlreadyExists: "Festivita gia presente.",
    holidayAdded: "Festivita aggiunta.",
    holidayRemoved: "Festivita rimossa.",
    holidayUpdated: "Festivita aggiornata.",
    holidayPasswordDescription: "Inserisci la password admin per confermare la festivita.",
    closureInvalidDate: "Seleziona una data valida.",
    closureRangeInvalid: "Seleziona un intervallo valido.",
    closureAlreadyExists: "Chiusura gia presente.",
    closureAdded: "Chiusura aggiunta.",
    closureRemoved: "Chiusura rimossa.",
    closureUpdated: "Chiusura aggiornata.",
    closurePasswordDescription: "Inserisci la password admin per confermare la chiusura.",
    closureNone: "Nessuna chiusura futura configurata.",
    requestUpdated: "Richiesta aggiornata.",
    requestConfirm: (typeLabel, startLabel, endLabel) =>
        `Confermi l'invio della richiesta di <strong>${typeLabel}</strong> dal <strong>${startLabel}</strong> al <strong>${endLabel}</strong>?`,
    mutuaConfirm: (startLabel, endLabel) =>
        `Confermi l'inserimento della <strong>Mutua</strong> dal <strong>${startLabel}</strong> al <strong>${endLabel}</strong>?`,
    giustificatoConfirm: (startLabel, endLabel) =>
        `Confermi l'inserimento del <strong>Permesso Giustificato</strong> dal <strong>${startLabel}</strong> al <strong>${endLabel}</strong>?`,
    specialeConfirm: (startLabel, endLabel) =>
        `Confermi l'inserimento del <strong>Permesso Chiusura Aziendale</strong> dal <strong>${startLabel}</strong> al <strong>${endLabel}</strong>?`,
    emptyDepartment: "Nessun reparto.",
    emptyEmployee: "Nessun operatore.",
    emptyAssignee: "Nessun dipendente",
    adminDeleteConfirm: (adminName) => `Confermi l'eliminazione dell'admin <strong>${adminName}</strong>?`,
    exportInvalidRange: "Seleziona un intervallo valido.",
    exportSelectType: "Seleziona almeno un tipo.",
    exportNoData: "Nessun dato da esportare.",
    exportSuccess: "File Excel creato con successo.",
    exportPasswordDescription: "Inserisci la password admin per esportare il calendario.",
    exportModuleMissingTitle: "Modulo 'xlsx' non trovato.",
    exportModuleMissingDetail: "Esegui 'npm install xlsx' nella cartella del progetto AyPi.",
    backupPasswordDescription: "Inserisci la password admin per accedere al backup.",
    backupSelectFolderTitle: "Seleziona la cartella di backup.",
    backupSelectFolderDetail: "Scegli la cartella del backup da ripristinare.",
    backupCreateSuccess: (folder) => `Backup creato in: ${folder}`,
    backupRestoreSuccess: "Ripristino completato.",
    backupRestoreConfirm: "Ripristinare il backup? I file attuali verranno sovrascritti.",
    backupCreateError: (detail) => `Errore durante il backup: ${detail}`,
    backupRestoreError: (detail) => `Errore durante il ripristino: ${detail}`,
    setupWizardTitle: "Configurazione iniziale",
    setupWizardMessage: "Completa la configurazione iniziale del calendario.",
    setupPathNote:
        "Nota: otp-mail.json non viene creato automaticamente. Se manca, il sistema usa il fallback locale.",
    mailConfigSaved: "Configurazione mailing salvata.",
    mailConfigError: (detail) => `Errore configurazione mailing: ${detail}`,
    mailTestSent: "Email di prova inviata.",
    mailTestError: (detail) => `Errore invio email di prova: ${detail}`,
    mailModuleMissing: "Modulo 'nodemailer' non disponibile.",
    dataSaveFailure: "Impossibile salvare i dati sul server.",
    adminsSaveFailure: "Impossibile salvare la lista admin.",
    assigneesReadFailure: "Impossibile leggere la lista dipendenti.",
    assigneesWriteFailure: "Impossibile salvare la lista dipendenti.",
    colorsReset: "Colori ripristinati.",
    initErrorTitle: "Errore inizializzazione ferie/permessi.",
    filterAccessTitle: "Abilitazione filtro",
    filterAccessDescription: (label) => `Inserisci la password admin per abilitare il filtro ${label}.`,
    setupAdminTitle: "Prima configurazione",
    setupAdminMessage: "Non esiste nessun admin. Inserisci il primo admin per iniziare.",
};

module.exports = { UI_TEXTS };
